# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: windows-latest


steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd '$(System.DefaultWorkingDirectory)'
        
        npm install
        npm run build
    displayName: 'npm install and build'

  - task: AzureFileCopy@4
    inputs:
      SourcePath: $(System.DefaultWorkingDirectory)/umd/index.min.js
      azureSubscription: 'azure-china-devops'
      Destination: 'AzureBlob'
      storage: 'ffc0st0media0ce2'
      ContainerName: 'ffc-js-sdk'
